{'author': 'PuntSistemes S.L.U., Odoo Community Association (OCA)',
 'auto_install': True,
 'category': 'After-Sales',
 'data': ['views/helpdesk_ticket_view.xml',
          'views/helpdesk_ticket_team_view.xml',
          'views/project_view.xml',
          'views/project_task_view.xml',
          'views/project_milestone.xml'],
 'depends': ['helpdesk_mgmt', 'project'],
 'development_status': 'Production/Stable',
 'license': 'AGPL-3',
 'name': 'Helpdesk Project',
 'summary': 'Add the option to select project in the tickets.',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/helpdesk'}
