{'author': 'Akretion, Tecnativa, Odoo Community Association (OCA)',
 'category': 'Accounting',
 'data': ['security/ir.access.csv',
          'data/sequence.xml',
          'report/report.xml',
          'report/report_checkdeposit.xml',
          'views/account_check_deposit_view.xml',
          'views/account_move_line_view.xml'],
 'depends': ['account'],
 'development_status': 'Mature',
 'installable': True,
 'license': 'AGPL-3',
 'name': 'Account Check Deposit',
 'summary': 'Manage deposit of checks to the bank',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/account-financial-tools'}
