{'application': False,
 'assets': {'web.assets_backend': ['base_tier_validation/static/src/components/**/*',
                                   'base_tier_validation/static/src/js/**/*']},
 'author': 'ForgeFlow, Odoo Community Association (OCA)',
 'category': 'Tools',
 'data': ['security/ir.access.csv',
          'data/cron_data.xml',
          'data/mail_data.xml',
          'views/tier_definition_view.xml',
          'views/tier_review_view.xml',
          'views/tier_validation_exception_view.xml',
          'wizard/comment_wizard_view.xml',
          'templates/tier_validation_templates.xml'],
 'depends': ['mail'],
 'development_status': 'Mature',
 'installable': True,
 'license': 'AGPL-3',
 'maintainers': ['LoisRForgeFlow'],
 'name': 'Base Tier Validation',
 'summary': 'Implement a validation process based on tiers.',
 'version': '20.0.1.3.0',
 'website': 'https://github.com/OCA/tier-validation'}
