{'application': True,
 'author': 'Gray Matter Logic, Odoo Community Association (OCA)',
 'category': 'Hidden',
 'data': ['security/ir.access.csv',
          'views/res_territory.xml',
          'views/res_branch.xml',
          'views/res_district.xml',
          'views/res_region.xml',
          'views/res_country.xml',
          'views/menu.xml'],
 'demo': ['demo/base_territory_demo.xml'],
 'depends': ['base'],
 'development_status': 'Production/Stable',
 'license': 'AGPL-3',
 'maintainers': ['max3903', 'brian10048'],
 'name': 'Base Territory',
 'summary': 'This module allows you to define territories, branches, districts and regions to be '
            'used for Field Service operations or Sales.',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/field-service'}
