{'application': True,
 'author': 'OpenERP SA,MONK Software, Tecnativa, ForgeFlow, Odoo Community Association (OCA)',
 'category': 'Knowledge',
 'data': ['data/ir_module_category.xml',
          'security/document_knowledge_security.xml',
          'data/res_users.xml',
          'views/document_knowledge.xml',
          'views/res_config.xml'],
 'demo': ['demo/document_knowledge.xml'],
 'depends': ['base'],
 'installable': True,
 'license': 'AGPL-3',
 'name': 'Documents Knowledge',
 'version': '20.0.1.0.1',
 'website': 'https://github.com/OCA/knowledge'}
