{'author': 'Gray Matter Logic, Odoo Community Association (OCA)',
 'category': 'Field Service',
 'data': ['security/res_groups.xml',
          'security/ir.access.csv',
          'views/fsm_vehicle.xml',
          'views/fsm_person.xml',
          'views/fsm_order.xml',
          'views/menu.xml'],
 'depends': ['fieldservice'],
 'development_status': 'Beta',
 'license': 'AGPL-3',
 'maintainers': ['max3903'],
 'name': 'Field Service Vehicles',
 'summary': 'Manage Field Service vehicles and assign drivers',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/field-service'}
