{'assets': {'web.assets_backend': ['/fieldservice_project/static/src/scss/project_column.scss']},
 'author': 'Pavlov Media, Odoo Community Association (OCA)',
 'category': 'Project',
 'data': ['views/project_views.xml',
          'views/project_task_views.xml',
          'views/fsm_location_views.xml',
          'views/fsm_order_views.xml',
          'security/ir.access.csv',
          'views/fsm_team.xml'],
 'depends': ['fieldservice', 'project'],
 'development_status': 'Beta',
 'installable': True,
 'license': 'AGPL-3',
 'name': 'Field Service - Project',
 'summary': 'Create field service orders from a project or project task',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/field-service'}
