{'application': False,
 'author': 'MASAR',
 'auto_install': False,
 'category': 'Marketing/Social Marketing',
 'data': ['security/ir.access.csv', 'views/account.xml'],
 'depends': ['social'],
 'external_dependencies': {'python': ['requests']},
 'installable': True,
 'license': 'AGPL-3',
 'name': 'Social · YouTube',
 'summary': 'YouTube channel connector — OAuth link, video upload, comment replies, insights',
 'version': '20.0.1.0.0',
 'website': 'https://masar.sa'}
