{'application': False,
 'assets': {'web.assets_backend': ['base_tier_validation_forward/static/src/xml/tier_review_template.xml']},
 'author': 'Ecosoft,Odoo Community Association (OCA)',
 'category': 'Tools',
 'data': ['security/ir.access.csv',
          'data/mail_data.xml',
          'views/tier_definition_view.xml',
          'wizard/forward_wizard_view.xml',
          'templates/tier_validation_templates.xml'],
 'depends': ['base_tier_validation'],
 'development_status': 'Alpha',
 'installable': True,
 'license': 'AGPL-3',
 'maintainers': ['kittiu'],
 'name': 'Base Tier Validation Forward',
 'summary': 'Forward option for base tiers',
 'uninstall_hook': 'uninstall_hook',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/tier-validation'}
