{'assets': {'web.assets_backend': ['queue_job/static/src/views/**/*']},
 'author': 'Camptocamp,ACSONE SA/NV,Odoo Community Association (OCA)',
 'category': 'Generic Modules',
 'data': ['security/security.xml',
          'security/ir.access.csv',
          'views/queue_job_views.xml',
          'views/queue_job_channel_views.xml',
          'views/queue_job_function_views.xml',
          'wizards/queue_jobs_to_done_views.xml',
          'wizards/queue_jobs_to_cancelled_views.xml',
          'wizards/queue_requeue_job_views.xml',
          'views/queue_job_menus.xml',
          'data/queue_data.xml',
          'data/queue_job_function_data.xml'],
 'depends': ['mail', 'base_sparse_field', 'web'],
 'development_status': 'Mature',
 'external_dependencies': {'python': ['requests', 'openupgradelib']},
 'installable': True,
 'license': 'LGPL-3',
 'maintainers': ['guewen', 'sbidoul'],
 'name': 'Job Queue',
 'post_init_hook': 'post_init_hook',
 'version': '20.0.2.1.4',
 'website': 'https://github.com/OCA/queue'}
