{'author': 'Gray Matter Logic, Odoo Community Association (OCA)',
 'auto_install': True,
 'category': 'Field Service',
 'data': ['security/ir.access.csv',
          'views/fsm_recurring.xml',
          'views/product_template.xml',
          'views/sale_order.xml'],
 'depends': ['fieldservice_recurring', 'fieldservice_sale', 'fieldservice_account'],
 'development_status': 'Beta',
 'installable': True,
 'license': 'AGPL-3',
 'maintainers': ['max3903', 'brian10048'],
 'name': 'Field Service - Sales - Recurring',
 'summary': 'Sell recurring field services.',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/field-service'}
