{'author': 'Tecnativa, BCIM, Okia, Odoo Community Association (OCA)',
 'category': 'Accounting',
 'data': ['security/ir.access.csv',
          'wizard/wizard_chart_update_view.xml',
          'views/account_config_settings_view.xml'],
 'depends': ['account'],
 'installable': True,
 'license': 'AGPL-3',
 'name': 'Detect changes and update the Account Chart from a template',
 'summary': "Wizard to update a company's account chart from a template",
 'version': '20.0.1.2.0',
 'website': 'https://github.com/OCA/account-financial-tools'}
