{'application': False,
 'author': 'MASAR',
 'category': 'Marketing/Social Marketing',
 'data': [],
 'depends': ['social', 'mcp_server'],
 'installable': True,
 'license': 'AGPL-3',
 'name': 'Social · MCP',
 'summary': 'Expose Social operations to the MASAR MCP tool layer',
 'version': '20.0.1.0.1',
 'website': 'https://masar.sa'}
