{'application': False,
 'assets': {'web.assets_frontend': ['fieldservice_portal/static/src/js/fsm_order_portal.esm.js']},
 'author': 'PyTech SRL, Odoo Community Association (OCA)',
 'category': 'Field Service',
 'data': ['security/ir.access.csv',
          'data/portal_entry_data.xml',
          'views/fsm_order_template.xml',
          'views/portal_template.xml',
          'views/fsm_stage.xml'],
 'demo': ['demo/fsm_location_demo.xml', 'demo/fsm_order_demo.xml'],
 'depends': ['fieldservice', 'portal'],
 'installable': True,
 'license': 'AGPL-3',
 'maintainers': ['aleuffre', 'renda-dev'],
 'name': 'Field Service - Portal',
 'summary': '\n    Bridge module between fieldservice and portal.\n    ',
 'version': '20.0.1.0.2',
 'website': 'https://github.com/OCA/field-service'}
