{'application': True,
 'assets': {'web.assets_backend': ['helpdesk_mgmt/static/src/views/**/*.esm.js',
                                   'helpdesk_mgmt/static/src/views/**/*.xml'],
            'web.assets_frontend': ['helpdesk_mgmt/static/src/js/new_ticket.esm.js'],
            'web.assets_unit_tests': ['helpdesk_mgmt/static/tests/**/*.test.js']},
 'author': 'AdaptiveCity, Tecnativa, ForgeFlow, C2i Change 2 Improve, Domatix, Factor Libre, SDi '
           'Soluciones, Odoo Community Association (OCA)',
 'category': 'After-Sales',
 'data': ['data/helpdesk_data.xml',
          'data/portal_entry_data.xml',
          'security/helpdesk_security.xml',
          'security/ir.access.csv',
          'views/res_partner_views.xml',
          'views/res_config_settings_views.xml',
          'views/helpdesk_ticket_templates.xml',
          'views/helpdesk_ticket_menu.xml',
          'views/helpdesk_ticket_team_views.xml',
          'views/helpdesk_ticket_stage_views.xml',
          'views/helpdesk_ticket_category_views.xml',
          'views/helpdesk_ticket_channel_views.xml',
          'views/helpdesk_ticket_tag_views.xml',
          'views/helpdesk_ticket_views.xml',
          'wizards/helpdesk_ticket_duplicate_wizard_views.xml'],
 'demo': ['demo/helpdesk_demo.xml'],
 'depends': ['mail', 'portal'],
 'development_status': 'Production/Stable',
 'installable': True,
 'license': 'AGPL-3',
 'name': 'Helpdesk Management',
 'summary': '\n        Helpdesk',
 'version': '20.0.1.1.2',
 'website': 'https://github.com/OCA/helpdesk'}
