{'application': True,
 'assets': {'web.assets_backend': ['social/static/src/scss/social_media.scss',
                                   'social/static/src/scss/social_inbox.scss',
                                   'social/static/src/views/social_inbox/**/*']},
 'author': 'MASAR',
 'category': 'Marketing/Social Marketing',
 'data': ['security/groups.xml',
          'security/ir.access.csv',
          'data/queue.xml',
          'views/social_views.xml',
          'views/provider_card_views.xml'],
 'depends': ['mail', 'utm', 'base_tier_validation', 'queue_job'],
 'installable': True,
 'license': 'AGPL-3',
 'name': 'Social',
 'summary': 'Publishing, customer interactions and social identities',
 'version': '20.0.2.1.1',
 'website': 'https://masar.sa'}
