{'author': 'Gray Matter Logic, Odoo Community Association (OCA)',
 'category': 'Field Service',
 'data': ['security/ir.access.csv',
          'views/fsm_person.xml',
          'views/fsm_order.xml',
          'views/purchase_order.xml'],
 'depends': ['fieldservice', 'purchase'],
 'development_status': 'Beta',
 'installable': True,
 'license': 'AGPL-3',
 'maintainers': ['max3903'],
 'name': 'Field Service - Purchase',
 'summary': 'Manage FSM purchases and link purchase orders to field service orders',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/field-service'}
