{'author': 'Gray Matter Logic, Odoo Community Association (OCA)',
 'category': 'Field Service',
 'data': ['data/ir_server_action.xml',
          'data/fsm_stage.xml',
          'data/base_automation.xml',
          'views/fsm_stage.xml'],
 'depends': ['fieldservice', 'base_automation'],
 'development_status': 'Beta',
 'installable': True,
 'license': 'AGPL-3',
 'maintainers': ['max3903'],
 'name': 'Field Service - Stage Server Action',
 'summary': 'Execute server actions when reaching a Field Service stage',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/field-service'}
