{'author': 'Patrick Wilson, Odoo Community Association (OCA)',
 'category': 'Field Service',
 'data': ['views/crm_lead.xml',
          'views/fsm_location.xml',
          'views/fsm_order.xml',
          'security/ir.access.csv'],
 'depends': ['fieldservice', 'crm'],
 'development_status': 'Beta',
 'installable': True,
 'license': 'AGPL-3',
 'maintainers': ['patrickrwilson'],
 'name': 'Field Service - CRM',
 'summary': 'Create Field Service orders from the CRM',
 'version': '20.0.1.0.1',
 'website': 'https://github.com/OCA/field-service'}
