{'application': False,
 'assets': {'web.assets_frontend': ['masar_website/static/src/scss/masar_website.scss',
                                    'masar_website/static/src/css/masar_pay.css',
                                    'masar_website/static/src/css/masar_brand_fix.css',
                                    'masar_website/static/src/css/masar_premium.css',
                                    'masar_website/static/src/css/masar_careers.css',
                                    'masar_website/static/src/js/masar_website.esm.js']},
 'author': 'MASAR',
 'auto_install': False,
 'category': 'Website',
 'data': ['data/website_menu.xml',
          'data/website_pwa.xml',
          'views/templates_components.xml',
          'views/templates_header.xml',
          'views/templates_homepage.xml',
          'views/templates_footer.xml',
          'views/templates_pages.xml',
          'views/templates_branding.xml',
          'views/content_refresh.xml',
          'views/templates_careers.xml',
          'data/website_sync.xml'],
 'depends': ['website', 'website_crm', 'website_hr_recruitment', 'mass_mailing', 'masar_theme'],
 'installable': True,
 'license': 'LGPL-3',
 'name': 'MASAR Website',
 'post_init_hook': 'post_init_hook',
 'summary': 'MASAR public website — bilingual marketing homepage, solutions, menus, and footer',
 'version': '20.0.1.19.2',
 'website': 'https://masar.sa'}
