{'assets': {'web._assets_primary_variables': ['document_page/static/src/**/document_page_variables.scss'],
            'web.assets_backend': ['document_page/static/src/scss/document_page.scss',
                                   'document_page/static/src/js/document_page_kanban_controller.esm.js',
                                   'document_page/static/src/js/document_page_kanban_view.esm.js']},
 'author': 'OpenERP SA, Odoo Community Association (OCA)',
 'category': 'Knowledge Management',
 'data': ['security/document_page_security.xml',
          'security/ir.access.csv',
          'wizard/document_page_create_menu.xml',
          'wizard/document_page_show_diff.xml',
          'views/document_page.xml',
          'views/document_page_category.xml',
          'views/document_page_history.xml',
          'views/report_document_page.xml'],
 'demo': ['demo/document_page.xml'],
 'depends': ['mail', 'document_knowledge', 'html_editor'],
 'images': ['images/category_list.png',
            'images/create_category.png',
            'images/page_list.png',
            'images/create_page.png',
            'images/customer_invoice.jpeg',
            'images/page_history.png'],
 'license': 'AGPL-3',
 'name': 'Document Page',
 'version': '20.0.1.0.2',
 'website': 'https://github.com/OCA/knowledge'}
