{'assets': {'voip_oca.agent_assets': ['voip_oca/static/lib/*.js'],
            'web.assets_backend': ['voip_oca/static/src/**/*'],
            'web.assets_unit_tests': ['voip_oca/static/tests/**/*']},
 'author': 'Dixmit, Odoo Community Association (OCA)',
 'category': 'Productivity/VOIP',
 'data': ['security/ir.access.csv',
          'views/res_users.xml',
          'views/voip_call.xml',
          'views/voip_pbx.xml',
          'views/menus.xml'],
 'demo': ['demo/demo_data.xml'],
 'depends': ['mail'],
 'excludes': ['voip'],
 'license': 'AGPL-3',
 'maintainers': ['etobella'],
 'name': 'Voip OCA',
 'summary': 'Provides the use of Voip',
 'version': '20.0.1.0.4',
 'website': 'https://github.com/OCA/connector-telephony'}
