{'application': False,
 'author': 'Konos, Open Source Integrators, Odoo Community Association (OCA)',
 'data': ['security/ir.access.csv',
          'views/helpdesk_ticket_type.xml',
          'views/helpdesk_ticket_team.xml',
          'views/helpdesk_ticket.xml',
          'views/res_config_settings_views.xml',
          'views/helpdesk_ticket_templates.xml'],
 'demo': ['demo/helpdesk_type_demo.xml'],
 'depends': ['helpdesk_mgmt'],
 'development_status': 'Beta',
 'license': 'AGPL-3',
 'maintainers': ['nelsonramirezs', 'max3903'],
 'name': 'Helpdesk Ticket Type',
 'summary': 'Add a type to your tickets',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/helpdesk'}
