{'application': False,
 'assets': {'web.report_assets_common': ['/partner_statement/static/src/scss/layout_statement.scss']},
 'author': 'ForgeFlow, Odoo Community Association (OCA)',
 'category': 'Accounting & Finance',
 'data': ['security/ir.access.csv',
          'security/statement_security.xml',
          'views/activity_statement.xml',
          'views/outstanding_statement.xml',
          'views/detailed_activity_statement.xml',
          'views/aging_buckets.xml',
          'views/res_config_settings.xml',
          'wizard/statement_wizard.xml'],
 'depends': ['account', 'report_xlsx', 'report_xlsx_helper'],
 'installable': True,
 'license': 'AGPL-3',
 'maintainers': ['MiquelRForgeFlow'],
 'name': 'Partner Statement',
 'summary': 'OCA Financial Reports',
 'version': '20.0.1.1.0',
 'website': 'https://github.com/OCA/account-financial-reporting'}
