{'application': False,
 'author': 'MASAR',
 'category': 'Marketing/Social Marketing',
 'data': ['security/ir.access.csv', 'data/cron.xml', 'views/account.xml'],
 'depends': ['social', 'base_setup'],
 'external_dependencies': {'python': ['facebook_business']},
 'installable': True,
 'license': 'AGPL-3',
 'name': 'Social · Meta',
 'summary': 'Meta Business SDK (v26) + Facebook Login; BrightBean-inspired connectors',
 'version': '20.0.1.4.0',
 'website': 'https://masar.sa'}
