{'application': False,
 'author': 'MASAR',
 'category': 'Knowledge',
 'data': ['security/groups.xml',
          'security/ir.access.csv',
          'data/ir_sequence_data.xml',
          'data/mail_activity_data.xml',
          'data/ir_cron_data.xml',
          'data/tier_definition_data.xml',
          'views/document_page_views.xml',
          'views/document_page_history_views.xml',
          'views/document_distribution_views.xml',
          'views/menus.xml',
          'wizard/distribute_document_views.xml'],
 'demo': [],
 'depends': ['document_page',
             'document_page_approval',
             'masar_knowledge',
             'mail',
             'hr',
             'base_tier_validation'],
 'installable': True,
 'license': 'AGPL-3',
 'name': 'Knowledge Control',
 'summary': 'Controlled documents on OCA Knowledge — types, versions, lifecycle, Tier Validation, '
            'distribution & acknowledgment',
 'version': '20.0.1.0.0',
 'website': 'https://masar.sa'}
