{'author': 'Savoir-faire Linux, Odoo Community Association (OCA)',
 'category': 'Knowledge Management',
 'data': ['security/ir.access.csv',
          'data/email_template.xml',
          'views/document_page_approval.xml',
          'security/document_page_security.xml'],
 'depends': ['document_page', 'mail'],
 'images': ['images/category.png', 'images/page_history_list.png', 'images/page_history.png'],
 'installable': True,
 'license': 'AGPL-3',
 'name': 'Document Page Approval',
 'post_init_hook': 'post_init_hook',
 'uninstall_hook': 'uninstall_hook',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/knowledge'}
