{'application': True,
 'assets': {'web._assets_core': ['equity/static/src/scss/security_class_ids_dropdown_menu.scss'],
            'web.assets_backend': ['equity/static/src/components/**/*.js',
                                   'equity/static/src/components/**/*.xml',
                                   'equity/static/src/components/**/*.scss',
                                   'equity/static/src/scss/*.scss'],
            'web.assets_frontend': ['equity/static/src/components/ubo_form/*',
                                    'equity/static/src/components/valuation_chart/*',
                                    'equity/static/src/scss/portal.scss',
                                    'web/static/src/views/fields/file_handler.js',
                                    'web/static/src/views/fields/file_handler.xml',
                                    'web/static/src/views/fields/formatters.js',
                                    'web/static/src/core/l10n/dates.js'],
            'web.assets_tests': ['equity/static/tests/tours/**/*']},
 'author': 'Odoo S.A.',
 'category': 'Accounting/Accounting',
 'data': ['data/mail_activity_type_data.xml',
          'data/mail_templates.xml',
          'security/equity_security.xml',
          'security/ir.access.csv',
          'views/equity_reporting_views.xml',
          'views/equity_security_class_views.xml',
          'views/equity_valuation_views.xml',
          'views/equity_transaction_views.xml',
          'views/equity_ubo_report.xml',
          'views/equity_ubo_views.xml',
          'views/mail_compose_message_views.xml',
          'views/res_partner_views.xml',
          'views/equity_menuitem.xml',
          'views/equity_portal_templates.xml',
          'views/equity_ubo_portal_templates.xml'],
 'demo': ['demo/demo_equity_security_class.xml',
          'demo/demo_equity_transaction.xml',
          'demo/demo_equity_ubo.xml',
          'demo/demo_equity_valuation.xml'],
 'depends': ['portal'],
 'installable': True,
 'license': 'LGPL-3',
 'name': 'Equity',
 'sequence': 31,
 'summary': 'Manage securities, transactions, and cap tables.',
 'version': '20.0.1.2.1'}
