{'author': 'Gray Matter Logic, Odoo Community Association (OCA)',
 'category': 'Field Service',
 'data': ['security/ir.access.csv',
          'views/fsm_person.xml',
          'views/fsm_category.xml',
          'views/fsm_person_skill.xml',
          'views/fsm_order.xml',
          'views/hr_skill.xml',
          'views/fsm_template.xml'],
 'depends': ['hr_skills', 'fieldservice'],
 'development_status': 'Beta',
 'installable': True,
 'license': 'AGPL-3',
 'maintainers': ['max3903'],
 'name': 'Field Service - Skills',
 'summary': 'Manage your Field Service workers skills',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/field-service'}
