{'author': 'Brian McMaster, Odoo Community Association (OCA)',
 'category': 'Field Service',
 'data': ['security/ir.access.csv',
          'views/fsm_size.xml',
          'views/fsm_location.xml',
          'views/fsm_order.xml',
          'views/menu.xml'],
 'depends': ['fieldservice', 'uom'],
 'development_status': 'Beta',
 'license': 'AGPL-3',
 'maintainers': ['brian10048'],
 'name': 'Field Service Sizes',
 'summary': 'Manage Sizes for Field Service Locations and Orders',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/field-service'}
