{'author': 'Tecnativa, Odoo Community Association (OCA)',
 'category': 'After-Sales',
 'data': ['security/ir.access.csv',
          'wizard/helpdesk_ticket_create_lead_views.xml',
          'views/crm_lead_view.xml',
          'views/helpdesk_ticket_view.xml'],
 'depends': ['helpdesk_mgmt', 'crm'],
 'installable': True,
 'license': 'AGPL-3',
 'maintainers': ['victoralmau'],
 'name': 'Link between Helpdesk and CRM',
 'summary': 'Links helpdesk tickets with leads',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/helpdesk'}
