{'application': True,
 'assets': {'web.assets_backend': ['account_financial_report/static/src/js/*',
                                   'account_financial_report/static/src/xml/**/*']},
 'author': 'Camptocamp,initOS GmbH,redCOR AG,ForgeFlow,Odoo Community Association (OCA)',
 'auto_install': False,
 'category': 'Reporting',
 'data': ['security/ir.access.csv',
          'wizard/aged_partner_balance_wizard_view.xml',
          'wizard/general_ledger_wizard_view.xml',
          'wizard/journal_ledger_wizard_view.xml',
          'wizard/open_items_wizard_view.xml',
          'wizard/trial_balance_wizard_view.xml',
          'wizard/vat_report_wizard_view.xml',
          'view/account_age_report_configuration_views.xml',
          'menuitems.xml',
          'reports.xml',
          'report/templates/layouts.xml',
          'report/templates/aged_partner_balance.xml',
          'report/templates/general_ledger.xml',
          'report/templates/journal_ledger.xml',
          'report/templates/open_items.xml',
          'report/templates/trial_balance.xml',
          'report/templates/vat_report.xml',
          'view/account_view.xml',
          'view/report_general_ledger.xml',
          'view/report_journal_ledger.xml',
          'view/report_trial_balance.xml',
          'view/report_open_items.xml',
          'view/report_aged_partner_balance.xml',
          'view/report_vat_report.xml',
          'view/res_config_settings_views.xml'],
 'depends': ['account', 'date_range', 'report_xlsx'],
 'installable': True,
 'license': 'AGPL-3',
 'name': 'Account Financial Reports',
 'summary': 'OCA Financial Reports',
 'version': '20.0.0.0.24',
 'website': 'https://github.com/OCA/account-financial-reporting'}
