{'author': 'Akretion,Vauxoo,Odoo Community Association (OCA)',
 'category': 'Accounting',
 'data': ['views/account_journal_views.xml',
          'views/account_move_views.xml',
          'security/ir.access.csv'],
 'demo': ['demo/ir_sequence_demo.xml', 'demo/account_journal_demo.xml'],
 'depends': ['account'],
 'installable': True,
 'license': 'AGPL-3',
 'maintainers': ['alexis-via', 'moylop260', 'luisg123v'],
 'name': 'Account Move Number Sequence',
 'post_init_hook': 'post_init_hook',
 'summary': 'Generate journal entry number from sequence',
 'version': '20.0.1.0.3',
 'website': 'https://github.com/OCA/account-financial-tools'}
