{'author': 'Gray Matter Logic, Odoo Community Association (OCA)',
 'category': 'Field Service',
 'data': ['security/ir.access.csv',
          'views/account_move.xml',
          'views/fsm_order.xml',
          'views/fsm_stage.xml'],
 'depends': ['fieldservice', 'account'],
 'development_status': 'Beta',
 'installable': True,
 'license': 'AGPL-3',
 'maintainers': ['osimallen', 'brian10048'],
 'name': 'Field Service - Accounting',
 'summary': 'Track invoices linked to Field Service orders',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/field-service'}
