{'author': 'GRAP, Akretion, Odoo Community Association (OCA)',
 'category': 'Accounting',
 'data': ['data/ir_module_category.xml',
          'security/res_groups.xml',
          'views/menu.xml',
          'views/res_config_settings_views.xml',
          'views/view_account_bank_statement.xml',
          'views/view_account_tag.xml',
          'views/view_account_move_line.xml'],
 'demo': ['demo/res_groups.xml'],
 'depends': ['account'],
 'installable': True,
 'license': 'AGPL-3',
 'maintainers': ['legalsylvain'],
 'name': 'Account - Missing Menus & Saxon Accounting',
 'summary': 'Adds missing menu entries for Account module and adds the option to enable Saxon '
            'Accounting',
 'version': '20.0.1.0.1',
 'website': 'https://github.com/OCA/account-financial-tools'}
