{'author': 'Gray Matter Logic, Odoo Community Association (OCA)',
 'category': 'Field Service',
 'data': ['security/res_groups.xml',
          'security/ir.access.csv',
          'views/fsm_location.xml',
          'views/fsm_order.xml',
          'views/product_template.xml',
          'views/sale_order.xml'],
 'depends': ['fieldservice', 'sale_management', 'fieldservice_account'],
 'development_status': 'Beta',
 'installable': True,
 'license': 'AGPL-3',
 'maintainers': ['max3903', 'brian10048'],
 'name': 'Field Service - Sales',
 'summary': 'Sell field services.',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/field-service'}
