{'assets': {'web.assets_backend': ['date_range/static/src/js/*']},
 'author': 'ACSONE SA/NV, Odoo Community Association (OCA)',
 'category': 'Uncategorized',
 'data': ['data/ir_cron_data.xml',
          'security/ir.access.csv',
          'views/date_range_view.xml',
          'wizard/date_range_generator.xml'],
 'depends': ['web'],
 'development_status': 'Mature',
 'installable': True,
 'license': 'LGPL-3',
 'maintainers': ['lmignon'],
 'name': 'Date Range',
 'summary': 'Manage all kind of date range',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/server-ux'}
