{'author': 'GARCO Consulting, Odoo Community Association (OCA)',
 'category': 'After-Sales',
 'data': ['views/helpdesk_sla_report.xml',
          'views/helpdesk_ticket_sla.xml',
          'security/ir.access.csv',
          'views/helpdesk_sla_views.xml',
          'views/helpdesk_ticket_views.xml',
          'views/helpdesk_ticket_team_views.xml'],
 'demo': ['demo/helpdesk_mgmt_sla_demo.xml'],
 'depends': ['base', 'helpdesk_mgmt', 'resource'],
 'license': 'AGPL-3',
 'name': 'Helpdesk Ticket SLA',
 'summary': 'Add SLA to the tickets for Helpdesk Management.',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/helpdesk'}
