{'author': 'Noviat, Odoo Community Association (OCA)',
 'category': 'Accounting & Finance',
 'data': ['security/ir.access.csv',
          'wizard/account_asset_compute.xml',
          'wizard/account_asset_remove.xml',
          'views/account_account.xml',
          'views/account_asset.xml',
          'views/account_asset_group.xml',
          'views/account_asset_profile.xml',
          'views/account_move.xml',
          'views/account_move_line.xml',
          'views/menuitem.xml',
          'data/cron.xml',
          'wizard/wiz_account_asset_report.xml',
          'wizard/wiz_asset_move_reverse.xml'],
 'depends': ['account', 'report_xlsx_helper'],
 'development_status': 'Mature',
 'excludes': ['account_asset'],
 'external_dependencies': {'python': ['python-dateutil']},
 'license': 'AGPL-3',
 'name': 'Assets Management',
 'version': '20.0.1.0.3',
 'website': 'https://github.com/OCA/account-financial-tools'}
