{'application': False,
 'author': 'APSL-Nagarro, Odoo Community Association (OCA)',
 'category': 'Field Service',
 'data': ['security/ir.access.csv',
          'views/fsm_blackout_day_templates.xml',
          'views/fsm_delivery_time_range_templates.xml',
          'views/fsm_stress_day_templates.xml',
          'views/fsm_route.xml',
          'views/menu.xml'],
 'demo': ['demo/fsm_blackout_day_demo.xml',
          'demo/fsm_blackout_group_demo.xml',
          'demo/fsm_delivery_time_range_demo.xml',
          'demo/fsm_stress_day_demo.xml'],
 'depends': ['fieldservice_route'],
 'installable': True,
 'license': 'AGPL-3',
 'maintainers': ['ppyczko'],
 'name': 'Fieldservice Availability',
 'summary': 'Provides models for defining blackout days, stress days, and delivery time ranges for '
            'FSM availability management.',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/field-service'}
