{'application': False,
 'author': 'MASAR',
 'category': 'Marketing/Social Marketing',
 'data': ['views/conversation.xml'],
 'depends': ['social', 'crm'],
 'installable': True,
 'license': 'AGPL-3',
 'name': 'Social · CRM',
 'summary': 'Bridge Social conversations to CRM leads',
 'version': '20.0.1.0.1',
 'website': 'https://masar.sa'}
