{'author': 'Gray Matter Logic, Brian McMaster, Odoo Community Association (OCA)',
 'category': 'Field Service',
 'data': ['security/ir.access.csv',
          'data/fsm_stock_data.xml',
          'views/res_territory.xml',
          'views/fsm_location.xml',
          'views/fsm_order.xml',
          'views/stock.xml',
          'views/stock_picking.xml',
          'views/fsm_person.xml'],
 'depends': ['fieldservice', 'stock'],
 'development_status': 'Beta',
 'license': 'AGPL-3',
 'maintainers': ['brian10048', 'max3903'],
 'name': 'Field Service - Stock',
 'summary': 'Integrate the logistics operations with Field Service',
 'version': '20.0.1.0.2',
 'website': 'https://github.com/OCA/field-service'}
