{'application': True,
 'assets': {'web.assets_backend': ['dms/static/src/models/*.js',
                                   'dms/static/src/js/fields/path_json/path_owl.esm.js',
                                   'dms/static/src/js/fields/preview_binary/preview_record.esm.js',
                                   'dms/static/src/js/views/*.esm.js',
                                   'dms/static/src/js/fields/path_json/path_owl.xml',
                                   'dms/static/src/js/fields/preview_binary/preview_record.xml',
                                   'dms/static/src/js/views/*.xml'],
            'web.assets_frontend': ['dms/static/src/scss/portal.scss'],
            'web.assets_tests': ['dms/static/tests/tours/**/*']},
 'author': 'MuK IT, Tecnativa, Odoo Community Association (OCA)',
 'category': 'Document Management',
 'data': ['security/security.xml',
          'security/ir.access.csv',
          'actions/file.xml',
          'template/portal.xml',
          'data/portal_entry_data.xml',
          'data/onboarding_data.xml',
          'views/dms_tag.xml',
          'views/dms_category.xml',
          'views/dms_file.xml',
          'views/dms_directory.xml',
          'views/storage.xml',
          'views/dms_access_groups_views.xml',
          'views/res_config_settings.xml',
          'views/menu.xml',
          'wizards/wizard_dms_file_move_views.xml',
          'wizards/wizard_dms_share_views.xml'],
 'demo': ['demo/res_users.xml',
          'demo/access_group.xml',
          'demo/category.xml',
          'demo/tag.xml',
          'demo/storage.xml',
          'demo/directory.xml',
          'demo/file.xml'],
 'depends': ['mail', 'http_routing', 'onboarding', 'portal', 'base', 'web'],
 'icon': '/dms/static/description/icon.png',
 'license': 'LGPL-3',
 'name': 'Document Management System',
 'summary': 'Document Management System for Odoo',
 'version': '20.0.1.1.2',
 'website': 'https://github.com/OCA/dms'}
