{'assets': {'web.assets_backend': ['report_xlsx/static/src/js/report/action_manager_report.esm.js']},
 'author': 'ACSONE SA/NV,Creu Blanca,Odoo Community Association (OCA)',
 'category': 'Reporting',
 'data': [],
 'demo': ['demo/report.xml'],
 'depends': ['base', 'web'],
 'development_status': 'Mature',
 'external_dependencies': {'python': ['xlsxwriter', 'xlrd']},
 'installable': True,
 'license': 'AGPL-3',
 'name': 'Base report xlsx',
 'summary': 'Base module to create xlsx report',
 'version': '20.0.1.0.2',
 'website': 'https://github.com/OCA/reporting-engine'}
