{'assets': {'web._assets_primary_variables': {'/web_responsive/static/src/legacy/scss/form_variable.scss',
                                              '/web_responsive/static/src/legacy/scss/primary_variable.scss'},
            'web.assets_backend': ['web_responsive/static/src/lib/fuse/fuse.basic.min.js',
                                   '/web_responsive/static/src/legacy/scss/web_responsive.scss',
                                   '/web_responsive/static/src/legacy/scss/big_boxes.scss',
                                   '/web_responsive/static/src/legacy/scss/list_sticky_header.scss',
                                   '/web_responsive/static/src/legacy/js/web_responsive.esm.js',
                                   '/web_responsive/static/src/legacy/xml/form_buttons.xml',
                                   '/web_responsive/static/src/legacy/xml/custom_favorite_item.xml',
                                   '/web_responsive/static/src/components/apps_menu_tools.esm.js',
                                   '/web_responsive/static/src/components/apps_menu/*',
                                   '/web_responsive/static/src/components/apps_menu_item/*',
                                   '/web_responsive/static/src/components/menu_canonical_searchbar/*',
                                   '/web_responsive/static/src/components/menu_odoo_searchbar/*',
                                   '/web_responsive/static/src/components/menu_fuse_searchbar/*',
                                   '/web_responsive/static/src/components/menu_searchbar/*',
                                   '/web_responsive/static/src/components/hotkey/*',
                                   '/web_responsive/static/src/components/file_viewer/*',
                                   '/web_responsive/static/src/components/chatter/*',
                                   '/web_responsive/static/src/components/control_panel/*',
                                   '/web_responsive/static/src/components/command_palette/*',
                                   '/web_responsive/static/src/views/form/*',
                                   ('remove', 'web_responsive/static/src/**/*.dark.scss')],
            'web.assets_clickbot': ['/web_responsive/static/src/clickbot/clickbot.esm.js'],
            'web.assets_web_dark': ['web_responsive/static/src/**/*.dark.scss'],
            'web.qunit_suite_tests': ['/web_responsive/static/tests/apps_menu_tests.esm.js',
                                      '/web_responsive/static/tests/apps_menu_search_tests.esm.js']},
 'author': 'LasLabs, Tecnativa, ITerra, Onestein, Odoo Community Association (OCA)',
 'category': 'Website',
 'data': ['views/res_users_views.xml'],
 'depends': ['web', 'web_tour', 'mail'],
 'development_status': 'Production/Stable',
 'excludes': ['web_enterprise'],
 'installable': False,
 'license': 'LGPL-3',
 'maintainers': ['Tardo', 'SplashS'],
 'name': 'Web Responsive',
 'sequence': 1,
 'summary': 'Responsive web client (disabled on SMART: needs full Owl 3 port; useState removed in Odoo 20)',
 'version': '20.0.1.1.0',
 'website': 'https://github.com/OCA/web'}
