{'application': False,
 'assets': {},
 'author': 'MASAR',
 'auto_install': False,
 'category': 'Hidden',
 'data': ['data/res_company_data.xml',
          'data/ir_config_parameter_data.xml',
          'data/website_data.xml'],
 'depends': ['base',
             'web',
             'mail',
             'contacts',
             'crm',
             'sale_management',
             'account',
             'project',
             'hr',
             'calendar',
             'website',
             'website_crm',
             'mass_mailing',
             'board'],
 'installable': True,
 'license': 'LGPL-3',
 'name': 'MASAR Brand',
 'post_init_hook': 'post_init_hook',
 'pre_init_hook': 'pre_init_hook',
 'summary': 'MASAR company branding, bilingual AR/EN defaults, and website readiness',
 'version': '20.0.1.0.3',
 'website': 'https://masar.sa'}
