{'author': 'Gray Matter Logic, Brian McMaster, Odoo Community Association (OCA)',
 'category': 'Field Service',
 'data': ['security/ir.access.csv',
          'views/fsm_equipment.xml',
          'views/product_template.xml',
          'views/stock_picking_type.xml',
          'views/stock_lot.xml'],
 'depends': ['fieldservice_stock'],
 'development_status': 'Beta',
 'license': 'AGPL-3',
 'maintainers': ['brian10048', 'max3903'],
 'name': 'Field Service - Stock Equipment',
 'summary': 'Integrate stock operations with your field service equipments',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/field-service'}
