{'author': 'Gray Matter Logic, Odoo Community Association (OCA)',
 'category': 'Field Service',
 'data': ['data/ir_sequence.xml',
          'data/fsm_route_day_data.xml',
          'data/fsm_stage_data.xml',
          'security/ir.access.csv',
          'views/fsm_route_day.xml',
          'views/fsm_route.xml',
          'views/fsm_location.xml',
          'views/fsm_route_dayroute.xml',
          'views/fsm_order.xml',
          'views/menu.xml'],
 'demo': ['demo/fsm_route.xml',
          'demo/fsm_location.xml',
          'demo/fsm_route_dayroute.xml',
          'demo/fsm_order.xml'],
 'depends': ['fieldservice'],
 'development_status': 'Beta',
 'license': 'AGPL-3',
 'maintainers': ['max3903'],
 'name': 'Field Service Route',
 'summary': 'Organize the routes of each day.',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/field-service'}
