{'author': 'Brian McMaster, Gray Matter Logic, Odoo Community Association (OCA)',
 'category': 'Field Service',
 'data': ['data/ir_sequence.xml',
          'security/res_groups.xml',
          'security/ir.access.csv',
          'views/fsm_frequency.xml',
          'views/fsm_frequency_set.xml',
          'views/fsm_order.xml',
          'views/fsm_recurring_template.xml',
          'views/fsm_recurring.xml',
          'views/fsm_team.xml',
          'data/recurring_cron.xml'],
 'demo': ['demo/frequency_demo.xml', 'demo/frequency_set_demo.xml', 'demo/recur_template_demo.xml'],
 'depends': ['fieldservice'],
 'development_status': 'Beta',
 'license': 'AGPL-3',
 'maintainers': ['max3903', 'brian10048'],
 'name': 'Field Service Recurring Work Orders',
 'summary': 'Manage recurring Field Service orders',
 'version': '20.0.1.0.0',
 'website': 'https://github.com/OCA/field-service'}
